# 异常处理要优雅 https://zhuanlan.zhihu.com/p/51800345?utm_source=wechatMessage_article_bottom

## 1.使用最多的 try catch

-   只能捕获运行时的同步代码
-   异步代码和语法错误不会被捕获

```js
try {
    Promise.reject('111');
} catch (err) {
    console.log('err', err);
}
```

以上代码不会打印错误信息

```js
try {
    rrr;
    Promise.reject('111');
} catch (err) {
    console.log('err', err);
}
```

会捕获错误，并打印 `err ReferenceError: rrr is not defined`

## 2. window.onerror

该方案有如下特点：

-   可以捕捉语法错误，也可以捕捉运行时错误；
-   可以拿到出错的信息，堆栈，出错的文件、行号、列号；
-   异步 setTimeOut 错误可以捕捉，没有 catch 的 Promise 不能够捕捉
-   不能捕捉静态资源异常，以及接口异常

```js
window.onerror = function (msg, url, line, col, error) {
    //没有URL不上报！上报也不知道错误
    if (msg != 'Script error.' && !url) {
        return true;
    }
    //采用异步的方式
    //我遇到过在window.onunload进行ajax的堵塞上报
    //由于客户端强制关闭webview导致这次堵塞上报有Network Error
    //我猜测这里window.onerror的执行流在关闭前是必然执行的
    //而离开文章之后的上报对于业务来说是可丢失的
    //所以我把这里的执行流放到异步事件去执行
    //脚本的异常数降低了10倍
    setTimeout(function () {
        var data = {};
        //不一定所有浏览器都支持col参数
        col = col || (window.event && window.event.errorCharacter) || 0;
        data.url = url;
        data.line = line;
        data.col = col;
        if (!!error && !!error.stack) {
            //如果浏览器有堆栈信息
            //直接使用
            data.msg = error.stack.toString();
        } else if (!!arguments.callee) {
            //尝试通过callee拿堆栈信息
            var ext = [];
            var f = arguments.callee.caller,
                c = 3;
            //这里只拿三层堆栈信息
            while (f && --c > 0) {
                ext.push(f.toString());
                if (f === f.caller) {
                    break; //如果有环
                }
                f = f.caller;
            }
            ext = ext.join(',');
            data.msg = error.stack.toString();
        }
        //把data上报到后台！
    }, 0);
    return true;
};
```

window.onerror 要在与错误代码在不同的代码块，原因：一旦出错，而没有执行 window.onerror 那就没有意义了
没有 catch 的 Promise.reject() 捕获不到

## 3.window.addEventListener

当一项资源（如图片或脚本）加载失败，加载资源的元素会触发一个 Event 接口的 error 事件，并执行该元素上的 onerror() 处理函数。这些 error 事件不会向上冒泡到 window ，不过（至少在 Firefox 中）能被单一的 window.addEventListener 捕获。

-   捕获未 catch 的 Promise

```js
window.addEventListener('unhandledrejection', function (e) {
    e.preventDefault();
    console.log('捕获到异常：', e);
    return true;
});

Promise.reject('promise error');
```

## 4.React 错误捕获

-   componentDidCatch()
-   错误边界(错误边界组件只能是 class 组件)
